Build system, CI, and linters (#21)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -8,6 +8,9 @@ on:
   pull_request:
   workflow_dispatch:
 
+permissions:
+  contents: read
+
 jobs:
   build:
     runs-on: ${{ matrix.os }}
@@ -24,21 +27,20 @@ jobs:
           - ubuntu-24.04
           - windows-2025
         exclude:
+          # cgo on Windows currently fails mysteriously, same as the other wasilibs repos.
           - os: windows-2025
             mode: cgo
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-go@v5
-        with:
-          go-version: '^1.25'
+      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+      - uses: curioswitch/go-build/.github/actions/setup-go@a2e54f5c6b6cff10d3b5ac6fcba4de7a411c6736 # v0.8.1
 
-      - name: setup autotools for cgo
+      - name: setup autotools for cgo (mac)
         if: ${{ matrix.mode == 'cgo' && startsWith(matrix.os, 'macos-') }}
         run: brew install autoconf automake libtool
 
       - name: setup libinjection for cgo
         if: ${{ matrix.mode == 'cgo' }}
-        run: |
+        run: |-
           wget https://github.com/libinjection/libinjection/archive/211782219663f889f471650150df12b623c5766e.tar.gz
           tar -xf 211782219663f889f471650150df12b623c5766e.tar.gz
           cd libinjection-211782219663f889f471650150df12b623c5766e
@@ -50,17 +52,19 @@ jobs:
 
       - name: setup tinygo
         if: ${{ matrix.mode == 'tinygo' }}
-        uses: acifani/setup-tinygo@v1
+        uses: acifani/setup-tinygo@dd8a7075d951a7595b2ef2123ed0ab1af0c13e56 # v3.0.0
         with:
           tinygo-version: 0.41.1
       - name: setup wasmtime for tinygo
         if: ${{ matrix.mode == 'tinygo' }}
         run: go install github.com/wasilibs/tools/cmd/wasmtime@13e21a5960c7f51cd8c92da5cf35774d3207ee38
 
-      - run: go run mage.go check
+      - name: run checks
+        run: go run ./build ${{ startsWith(matrix.os, 'ubuntu-') && 'check' || 'test' }}
         env:
-          WASI_TEST_MODE: ${{ matrix.mode }}
+          LIBINJECTION_TEST_MODE: ${{ matrix.mode }}
           LD_LIBRARY_PATH: ${{ startsWith(matrix.os, 'ubuntu-') && matrix.mode == 'cgo' && '/usr/local/lib' || '' }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   # Runs tests using wazero inside a minimal golang docker image. This makes sure the code builds
   # even when there is no C toolchain available. It is possible for code to work fine with CGO_ENABLED=0
@@ -71,8 +75,8 @@ jobs:
     container:
       image: golang:alpine
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
 
-      - run: if command -v gcc &> /dev/null; then echo "GCC found but not expected"; exit 321; fi
+      - run: if command -v gcc &> /dev/null; then echo "GCC found but not expected"; exit 2; fi
 
-      - run: go run mage.go test
+      - run: go run ./build test-go
